---
title: "Richness Comparisons"
author: "Philip S. Mostert"
date: "2023-09-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Load packages}

library(intSDM)
library(INLA)
library(dplyr)

```

```{r Load in Data locally}

Tron <- readRDS('~/Downloads/regionGeometry.RDS')
dt <- readRDS('~/Downloads/processedDataForPhil.RDS')

```

```{r Create mesh and SPDE}

#Tron <- st_transform(Tron,'+proj=utm +zone=32 +ellps=WGS84 +datum=WGS84 +units=m +no_defs')

#mesh <- INLA::inla.mesh.2d(boundary = inlabru::fm_as_segm(Tron),
#                           loc = st_as_sfc(dt),
#                           cutoff = 9000, max.edge=c(8000, 12000), offset= 800,
#                           crs = inlabru::fm_crs('+proj=utm +zone=32 +ellps=WGS84 +datum=WGS84 +units=m +no_defs'))
#ggplot() + geom_sf(data = Tron) + gg(mesh)

mesh <- INLA::inla.mesh.2d(boundary = inlabru::fm_as_segm(Tron),
                           loc = st_as_sfc(dt),
                           cutoff = 11000, max.edge=c(39000, 46000), offset= 80000,
                           crs = inlabru::fm_crs('+proj=utm +zone=32 +ellps=WGS84 +datum=WGS84 +units=m +no_defs'))

spatMod <- inla.spde2.matern(mesh = mesh)

```

```{r Find unique locations}

#dt <- st_transform(dt, mesh$crs) 

dt$simpleScientificName <- as.numeric(as.factor(dt$simpleScientificName))

uniqueLocations <- c(st_equals(dt))[!duplicated(lapply( c(st_equals(dt)), sort))]

dt$samplingSite <- NA

for (i in 1:length(uniqueLocations)) dt[unlist(uniqueLocations[[i]]), 'samplingSite'] <- i

```

```{r Split data up}

PO <- dt[dt$dataType == 'PO',]
PA <- dt[dt$dataType != 'PO',]

```

```{r Create Likelihoods}

#Most occurring == 4,17,21,7,31,1

PALike <- like(formula = individualCount ~ .,
               data = PA[PA$simpleScientificName %in% c(4,17,21,7,31),],
               family = 'Binomial',
               include = c('PAintercept', 'PASpde'), 
               control.family = list(link = 'cloglog'))

POLike <- like(formula = geometry ~ .,
               data = PO[PO$simpleScientificName %in% c(4,17, 21,7,31),],
               family = 'cp',
               include = c('POintercept', 'POSpde'),
               ips = fm_int(domain = mesh, samplers = Tron))

species4Like <- like(formula = individualCount ~ .,
                     data = dt[dt$simpleScientificName == 4,],
                     family = 'Poisson',
                     include = c('species4Intercept', 'species4effect'))

species17Like <- like(formula = individualCount ~ .,
                     data = dt[dt$simpleScientificName == 17,],
                     family = 'Poisson',
                     include = c('species17Intercept', 'species17effect'))

species21Like <- like(formula = individualCount ~ .,
                     data = dt[dt$simpleScientificName == 21,],
                     family = 'Poisson',
                     include = c('species21Intercept', 'species21effect'))

species7Like <- like(formula = individualCount ~ .,
                     data = dt[dt$simpleScientificName == 7,],
                     family = 'Poisson',
                     include = c('species7Intercept', 'species7effect'))

species31Like <- like(formula = individualCount ~ .,
                     data = dt[dt$simpleScientificName == 31,],
                     family = 'Poisson',
                     include = c('species31Intercept', 'species31effect'))

```

```{r Components}

 
Components <- ~ - 1 +
                PAintercept(1) + 
                POintercept(1) + 
                species4Intercept(1) + 
                species17Intercept(1) + 
                species21Intercept(1) + 
                species7Intercept(1) + 
                species31Intercept(1) +
                POSpde(main = geometry, model = spatMod) + 
                PASpde(main = geometry, copy = 'POSpde', hyper = list(beta = list(fixed = FALSE))) +
                species4effect(main = geometry, model = spatMod) + 
                species17effect(main = geometry, copy = 'species4effect', hyper = list(beta = list(fixed = FALSE))) +
                species21effect(main = geometry, copy = 'species4effect', hyper = list(beta = list(fixed = FALSE))) +
                species7effect(main = geometry, copy = 'species4effect', hyper = list(beta = list(fixed = FALSE))) +
                species31effect(main = geometry, copy = 'species4effect', hyper = list(beta = list(fixed = FALSE)))
  

```

```{r Model}

Model <- bru(components = Components,
             PALike,
             POLike,
             species4Like,
             species17Like,
             species21Like,
             species7Like,
             species31Like,
             options = list(num.threads = 4))

summary(Model)

```

```{r Preds}

Pixels <- fm_pixels(mesh = mesh, mask = st_transform(Tron, mesh$crs))
Preds1 <- predict(Model, newdata = Pixels, formula = ~ species4effect + species17effect + species21effect + species7effect + species31effect)
ggplot() + gg(Preds1, aes(col = mean))

```

```{r Components 2}

Components2 <- ~ - 1 +
                PAintercept(1) + 
                POintercept(1) + 
                species4Intercept(1) + 
                species17Intercept(1) + 
                species21Intercept(1) + 
                species7Intercept(1) + 
                species31Intercept(1) +
                POSpde(main = geometry, model = spatMod) + 
                PASpde(main = geometry, copy = 'POSpde', hyper = list(beta = list(fixed = FALSE))) +
                species4effect(main = geometry, model = spatMod) + 
                species17effect(main = geometry, model = spatMod) +
                species21effect(main = geometry, model = spatMod) +
                species7effect(main = geometry, model = spatMod) +
                species31effect(main = geometry, model = spatMod)

```

```{r Model 2}

Model2 <- bru(components = Components2,
              PALike,
              POLike,
              species4Like,
              species17Like,
              species21Like,
              species7Like,
              species31Like,
              options = list(num.threads = 4))

summary(Model2)

```

```{r Preds 2}

Preds2 <- predict(Model2, newdata = Pixels, formula = ~ species4effect + species17effect + species21effect + species7effect + species31effect)
ggplot() + gg(Preds2, aes(col = mean))

```

```{r Components 3}

SpeciesLike <- like(formula = individualCount ~ .,
                     data = dt,
                     include = c('SpeciesIntercept', 'siteIndex'),
                     family = 'Poisson')

Components3 <- ~ - 1 + PAintercept(1) + POintercept(1) + SpeciesIntercept(1) +
                POSpde(main = geometry, model = spatMod) + 
                PASpde(main = geometry, copy = 'POSpde', hyper = list(beta = list(fixed = FALSE))) +
                #speciesIndex(simpleScientificName, model = 'iid',   
                #             hyper = list(prec = list(initial = -log(0.001),
                #                                      fixed = TRUE))) +
                siteIndex(main = geometry, model = spatMod, group = simpleScientificName, ngroup = 5, control.group = list(model = 'iid'))

```


```{r Model3}

Model3 <- bru(components = Components3,
              PALike,
              POLike,
              SpeciesLike,
              options = list(num.threads = 4))
```

```{r Predict 3}

Dat <- fm_cprod(fm_pixels(mesh = mesh, mask = st_transform(Tron, mesh$crs)), 
                data.frame(simpleScientificName = 1:max(dt$simpleScientificName)))

Preds3 <- predict(Model3, newdata = Dat, formula =  ~ siteIndex)

ggplot() + gg(Preds3 %>% group_by(geometry) %>% summarise(su = sum(mean)), aes(col = su))


```
